
import java.io.File;
import java.rmi.AlreadyBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Josue Rodriguez
 */
public final class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     * @throws java.rmi.RemoteException
     */
    public Servidor() throws RemoteException, AlreadyBoundException {
        initComponents();
        
        //Preparar el directorio para enviarlo a la cache del cliente
        // System.out.println("Deberia hacer esto...");
        directorioRaiz.setName("Root");
        directorioRaiz = cargarDirectorioEnCache("./Root",directorioRaiz);
        directorioRaiz.printDirectories("-",directorioRaiz);
        //Cargar arbolito 
        DefaultMutableTreeNode r = new DefaultMutableTreeNode("Root");
        cargarDirectorio(directorioRaiz,r);
        this.arbolServidor.setModel(new DefaultTreeModel(r));
        //System.out.println("Lo hizo?");
        
        //Iniciar servidor
        server = new Com("Servidor",directorioRaiz);
        Registry registry = LocateRegistry.createRegistry(4200);
        registry.bind("proyecto", server);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolServidor = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");

        jButton1.setText("¿Qué soy?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(arbolServidor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Este es el servidor");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Servidor().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (AlreadyBoundException ex) {
                    Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    /*public void cargarDirectorio(String root, DefaultMutableTreeNode nodo){
        File directory = new File(root);
        File[] list = directory.listFiles();
        for(File file: list){
            if(file.isFile()){
                String nombre = file.getName();
                nodo.add(new DefaultMutableTreeNode(nombre));
                //System.out.println("Archivo: " + file.getName());
                //System.out.println("Parent: " + getParentName(file.getParent()));
                
            }else if(file.isDirectory()){
                DefaultMutableTreeNode subDirectory = new DefaultMutableTreeNode(file.getName());
                cargarDirectorio(file.getAbsolutePath(),subDirectory);
                nodo.add(subDirectory);
            }
        }
    }*/
    
    public void cargarDirectorio(Directory dir, DefaultMutableTreeNode nodo){
        for (int i = 0; i < dir.subdirectorios.size(); i++) {
            DefaultMutableTreeNode subDirectory = new DefaultMutableTreeNode(dir.subdirectorios.get(i).dirName);
            cargarDirectorio(dir.subdirectorios.get(i),subDirectory);
            nodo.add(subDirectory);
        }
        for (int i = 0; i < dir.archivos.size(); i++) {
            nodo.add(new DefaultMutableTreeNode(dir.archivos.get(i).getName()));
        }
    }
    
    public Directory cargarDirectorioEnCache(String root, Directory dirs){
        File directory = new File(root);
        dirs.setName(directory.getName());
        File[] list = directory.listFiles();
        for (File file : list) {
            if(file.isFile()){
                //System.out.println("hizo un pushFile");
                dirs.pushFile(file);
            }else if(file.isDirectory()){
                //System.out.println("hizo un pushDirectory");
                dirs.pushDirectory(cargarDirectorioEnCache(file.getAbsolutePath(),new Directory()));
                //dirs.imprimirDirectorios();
            }
        }
        return dirs;
    }
    
    
    
    public static String getParentName(String parent){
        String retVal = "";
        String retValReversed = "";
        //System.out.println("Parent received: " + parent);
        //System.out.println(parent.length()-1);
        for (int i = parent.length()-1; i >= 0 ; i--) {
            //System.out.println("i = " + i);
            //System.out.println("entro al if");
            if(parent.charAt(i)== '\\'){
                i = -1;
            }else{
                retVal += parent.charAt(i);
                //System.out.println("concateno a parent");
            }
        }
        for (int i = retVal.length()-1; i >= 0; i--) {
            retValReversed += retVal.charAt(i);
        }
        return retValReversed;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolServidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    Com server;
    Directory directorioRaiz = new Directory();
}
